<a href="https://colab.research.google.com/github/kamrulhuda/Time_Series_Analysis/blob/main/Features_and_Labels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset= tf.data.Dataset.range(20)
for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [4]:
dataset= tf.data.Dataset.range(20)
dataset = dataset.window(3, shift=2, drop_remainder=False)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end= " ")
  print()

0 1 2 
2 3 4 
4 5 6 
6 7 8 
8 9 10 
10 11 12 
12 13 14 
14 15 16 
16 17 18 
18 19 


In [6]:
dataset= tf.data.Dataset.range(20)
dataset = dataset.window(3, shift=5, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end= " ")
  print()

0 1 2 
5 6 7 
10 11 12 
15 16 17 


In [9]:
dataset= tf.data.Dataset.range(20)
dataset = dataset.window(3, shift=2, drop_remainder=True)
dataset= dataset.flat_map(lambda window:window.batch(5))
for window in dataset:
  print(window.numpy())

[0 1 2]
[2 3 4]
[4 5 6]
[6 7 8]
[ 8  9 10]
[10 11 12]
[12 13 14]
[14 15 16]
[16 17 18]


In [13]:
dataset= tf.data.Dataset.range(20)
dataset = dataset.window(3, shift=2, drop_remainder=True)
dataset= dataset.flat_map(lambda window:window.batch(5))
dataset= dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1] [2]
[2 3] [4]
[4 5] [6]
[6 7] [8]
[8 9] [10]
[10 11] [12]
[12 13] [14]
[14 15] [16]
[16 17] [18]


In [17]:
dataset= tf.data.Dataset.range(20)
dataset = dataset.window(3, shift=2, drop_remainder=True)
dataset= dataset.flat_map(lambda window:window.batch(5))
dataset= dataset.map(lambda window: (window[:-1], window[-1:]))
dataset= dataset.shuffle(buffer_size=5)
for x,y in dataset:
  print(x.numpy(), y.numpy())

[4 5] [6]
[0 1] [2]
[6 7] [8]
[10 11] [12]
[12 13] [14]
[2 3] [4]
[14 15] [16]
[8 9] [10]
[16 17] [18]


In [7]:
dataset= tf.data.Dataset.range(100)
dataset = dataset.window(10, shift=5, drop_remainder=True)
dataset= dataset.flat_map(lambda window:window.batch(5))
dataset= dataset.map(lambda window: (window[:-1], window[-1:]))
dataset= dataset.shuffle(buffer_size=5)
dataset= dataset.batch(20).prefetch(1)
for x,y in dataset:
  print("X= " ,x.numpy() )
  print("Y= " ,y.numpy() )

X=  [[ 5  6  7  8]
 [10 11 12 13]
 [ 5  6  7  8]
 [20 21 22 23]
 [20 21 22 23]
 [10 11 12 13]
 [25 26 27 28]
 [25 26 27 28]
 [15 16 17 18]
 [35 36 37 38]
 [30 31 32 33]
 [30 31 32 33]
 [40 41 42 43]
 [40 41 42 43]
 [45 46 47 48]
 [35 36 37 38]
 [50 51 52 53]
 [45 46 47 48]
 [ 0  1  2  3]
 [60 61 62 63]]
Y=  [[ 9]
 [14]
 [ 9]
 [24]
 [24]
 [14]
 [29]
 [29]
 [19]
 [39]
 [34]
 [34]
 [44]
 [44]
 [49]
 [39]
 [54]
 [49]
 [ 4]
 [64]]
X=  [[60 61 62 63]
 [50 51 52 53]
 [65 66 67 68]
 [55 56 57 58]
 [70 71 72 73]
 [55 56 57 58]
 [75 76 77 78]
 [80 81 82 83]
 [65 66 67 68]
 [70 71 72 73]
 [80 81 82 83]
 [15 16 17 18]
 [90 91 92 93]
 [90 91 92 93]
 [85 86 87 88]
 [95 96 97 98]
 [75 76 77 78]
 [85 86 87 88]]
Y=  [[64]
 [54]
 [69]
 [59]
 [74]
 [59]
 [79]
 [84]
 [69]
 [74]
 [84]
 [19]
 [94]
 [94]
 [89]
 [99]
 [79]
 [89]]
